# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping_list.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13shopping_list.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x13NewShoppingListItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\r\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"R\n\x10ShoppingListItem\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\r\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"\x12\n\x03Uid\x12\x0b\n\x03uid\x18\x01 \x01(\t2\xb1\x02\n\x0cShoppingList\x12@\n\x0fGetShoppingList\x12\x16.google.protobuf.Empty\x1a\x11.ShoppingListItem\"\x00\x30\x01\x12\x30\n\x13GetShoppingListItem\x12\x04.Uid\x1a\x11.ShoppingListItem\"\x00\x12\x36\n\x16\x43reateShoppingListItem\x12\x14.NewShoppingListItem\x1a\x04.Uid\"\x00\x12@\n\x16UpdateShoppingListItem\x12\x11.ShoppingListItem\x1a\x11.ShoppingListItem\"\x00\x12\x33\n\x16\x44\x65leteShoppingListItem\x12\x04.Uid\x1a\x11.ShoppingListItem\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_list_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWSHOPPINGLISTITEM._serialized_start=52
  _NEWSHOPPINGLISTITEM._serialized_end=124
  _SHOPPINGLISTITEM._serialized_start=126
  _SHOPPINGLISTITEM._serialized_end=208
  _UID._serialized_start=210
  _UID._serialized_end=228
  _SHOPPINGLIST._serialized_start=231
  _SHOPPINGLIST._serialized_end=536
# @@protoc_insertion_point(module_scope)
