# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import shopping_list_pb2 as shopping__list__pb2


class ShoppingListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShoppingList = channel.unary_stream(
                '/ShoppingList/GetShoppingList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=shopping__list__pb2.ShoppingListItem.FromString,
                )
        self.GetShoppingListItem = channel.unary_unary(
                '/ShoppingList/GetShoppingListItem',
                request_serializer=shopping__list__pb2.Uid.SerializeToString,
                response_deserializer=shopping__list__pb2.ShoppingListItem.FromString,
                )
        self.CreateShoppingListItem = channel.unary_unary(
                '/ShoppingList/CreateShoppingListItem',
                request_serializer=shopping__list__pb2.NewShoppingListItem.SerializeToString,
                response_deserializer=shopping__list__pb2.Uid.FromString,
                )
        self.UpdateShoppingListItem = channel.unary_unary(
                '/ShoppingList/UpdateShoppingListItem',
                request_serializer=shopping__list__pb2.ShoppingListItem.SerializeToString,
                response_deserializer=shopping__list__pb2.ShoppingListItem.FromString,
                )
        self.DeleteShoppingListItem = channel.unary_unary(
                '/ShoppingList/DeleteShoppingListItem',
                request_serializer=shopping__list__pb2.Uid.SerializeToString,
                response_deserializer=shopping__list__pb2.ShoppingListItem.FromString,
                )


class ShoppingListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShoppingList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShoppingListItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateShoppingListItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShoppingListItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShoppingListItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoppingListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShoppingList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShoppingList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=shopping__list__pb2.ShoppingListItem.SerializeToString,
            ),
            'GetShoppingListItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShoppingListItem,
                    request_deserializer=shopping__list__pb2.Uid.FromString,
                    response_serializer=shopping__list__pb2.ShoppingListItem.SerializeToString,
            ),
            'CreateShoppingListItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShoppingListItem,
                    request_deserializer=shopping__list__pb2.NewShoppingListItem.FromString,
                    response_serializer=shopping__list__pb2.Uid.SerializeToString,
            ),
            'UpdateShoppingListItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShoppingListItem,
                    request_deserializer=shopping__list__pb2.ShoppingListItem.FromString,
                    response_serializer=shopping__list__pb2.ShoppingListItem.SerializeToString,
            ),
            'DeleteShoppingListItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShoppingListItem,
                    request_deserializer=shopping__list__pb2.Uid.FromString,
                    response_serializer=shopping__list__pb2.ShoppingListItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShoppingList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShoppingList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShoppingList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ShoppingList/GetShoppingList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            shopping__list__pb2.ShoppingListItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShoppingListItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShoppingList/GetShoppingListItem',
            shopping__list__pb2.Uid.SerializeToString,
            shopping__list__pb2.ShoppingListItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateShoppingListItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShoppingList/CreateShoppingListItem',
            shopping__list__pb2.NewShoppingListItem.SerializeToString,
            shopping__list__pb2.Uid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateShoppingListItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShoppingList/UpdateShoppingListItem',
            shopping__list__pb2.ShoppingListItem.SerializeToString,
            shopping__list__pb2.ShoppingListItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteShoppingListItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShoppingList/DeleteShoppingListItem',
            shopping__list__pb2.Uid.SerializeToString,
            shopping__list__pb2.ShoppingListItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
